#!/bin/bash

echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"
hugo -t hyde --buildDrafts

msg="rebuilding site `date`"
if [ $# -eq 1 ]
  then msg="$1"
fi

# Commit site sources
git add -A && \
git commit -m "$msg" && \
git push origin master

# Commit public
(
cd public && \
git add -A && \
git commit -m "$msg" && \
git push origin master
)